export default [
  {
    name: "Codo 2x45 SAL",
    img: "1.Codo 2x45 SAL Tuboplast.webp",
    img1: "1.Codo 2x45 SAL Tuboplast.webp",
    img2: "1.Codo 2x45 SAL Tuboplast.webp",
    img3: "1.Codo 2x45 SAL Tuboplast.webp",
    descripcion:
      "Realiza correctamente las instalaciones de desagüe de tu hogar con este codo elaborado con material de CPVC y gran capacidad de durabilidad; además, es resistente a altas temperaturas, lo cual asegura su prolongado periodo de utilidad.",
    marca: "Tuboplast",
    ancho: "17 cm",
    profundidad: "6 cm",
    alto: "18 cm",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "0.390 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Sombrero PVC 2¨",
    img: "2.Sombrero PVC 2 .webp",
    img1: "2.Sombrero PVC 2 .webp",
    img2: "2.Sombrero PVC 2 .webp",
    img3: "2.Sombrero PVC 2 .webp",
    descripcion:
      "El sombrero, es un accesorio plástico que evita que los malos olores salgan del tanque.",
    marca: "Tuboplast",
    ancho: "16 cm",
    profundidad: "6 cm",
    alto: "16 cm",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "0.490 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Codo 4x90 SAL",
    img: "Codo 4x90 sal Tuboplast.webp",
    img1: "Codo 4x90 sal Tuboplast.webp",
    img2: "Codo 4x90 sal Tuboplast.webp",
    img3: "Codo 4x90 sal Tuboplast.webp",
    descripcion:
      "Accesorio que permite conectar cuatro tuberías de fluidos en desagües. Longitud de campana: 4 cm.",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "15 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "0.125 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Codo 2x90 SAL",
    img: "Codo 2x90 SAL.webp",
    img1: "Codo 2x90 SAL.webp",
    img2: "Codo 2x90 SAL.webp",
    img3: "Codo 2x90 SAL.webp",
    descripcion:
      "Tubería ideal para fluidos en desagües. Diámetro de campana: 5.42 cm. Longitud de campana: 5.2 cm. Espesor: 0.15 cm.",
    tipo: "Codo",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "13 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "0.062 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Tubo S.Presion 1/2¨",
    img: "tubo simple presion 1-2.webp",
    img1: "tubo simple presion 1-2.webp",
    img2: "tubo simple presion 1-2.webp",
    img3: "tubo simple presion 1-2.webp",
    descripcion:
      "Sistema de agua para conducción de fluidos a presión. Espesor de 1.8 mm.",
    tipo: "tuberia",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "",
    longitud: "500 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "0.813 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Codo roscado 90° 1/2¨",
    img: "Codo roscado 90° 1-2¨.webp",
    img1: "Codo roscado 90° 1-2¨.webp",
    img2: "Codo roscado 90° 1-2¨.webp",
    img3: "Codo roscado 90° 1-2¨.webp",
    descripcion:
      "Tubería para fluidos. Diámetro exterior: 2.1 cm. Diámetro de campana: 2.12 cm. Longitud de campana: 4.5 cm. Espesor: 0.45 cm.",
    tipo: "Codo",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "4.5 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "0.04 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Yee 4¨ a 2¨ SAL",
    img: "Yee  4 a 2  SAL.webp",
    img1: "Yee  4 a 2  SAL.webp",
    img2: "Yee  4 a 2  SAL.webp",
    img3: "Yee  4 a 2  SAL.webp",
    descripcion:
      "El tubo Yee, es un accesorio hecho de PVC ideal para trabajos de gasfitería en el desagüe.",
    tipo: "Codo",
    marca: "Tuboplast",
    ancho: "21 cm",
    profundidad: "7 cm",
    alto: "28 cm",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "0.405 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Codo 4¨ a 2¨ SAL",
    img: "Codo 4¨ a 2¨ SAL.webp",
    img1: "Codo 4¨ a 2¨ SAL.webp",
    img2: "Codo 4¨ a 2¨ SAL.webp",
    img3: "Codo 4¨ a 2¨ SAL.webp",
    descripcion:
      "Realiza correctamente las instalaciones de desagüe de tu hogar con este codo elaborado con material de PVC y gran capacidad de durabilidad; además, es resistente a altas temperaturas, lo cual asegura su prolongado periodo de utilidad.",
    tipo: "Codo",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Unión 4¨ SAL",
    img: "Unión 4 SAL Tuboplast.webp",
    img1: "Unión 4 SAL Tuboplast.webp",
    img2: "Unión 4 SAL Tuboplast.webp",
    img3: "Unión 4 SAL Tuboplast.webp",
    descripcion:
      "Accesorio que permite conectar cuatro tuberías de fluidos en desagües. Longitud de campana: 6 cm.",
    tipo: "Yee",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "28 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "0.535 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Reduccion de 4¨ a 2¨ SAL",
    img: "Reduccion de 4¨ a 2¨ SAL .webp",
    img1: "Reduccion de 4¨ a 2¨ SAL .webp",
    img2: "Reduccion de 4¨ a 2¨ SAL .webp",
    img3: "Reduccion de 4¨ a 2¨ SAL .webp",
    descripcion:
      "Facilita la fluida transmisión de líquidos y encajado. Cuenta con capacidad resistente y bajo nivel de corrosión, garantiza un prolongado periodo de utilidad y pureza del agua. Accesorio que permite conectar cuatro tuberías de fluidos en desagües. Longitud de campana: 4.5 cm.",
    tipo: "Yee",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "15.5 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "0.155 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Tee sanitaria de 4x4",
    img: "Tee sanitaria de 4x4 Tuboplast.webp",
    img1: "Tee sanitaria de 4x4 Tuboplast.webp",
    img2: "Tee sanitaria de 4x4 Tuboplast.webp",
    img3: "Tee sanitaria de 4x4 Tuboplast.webp",
    descripcion:
      "Realizaras empalmes en las tuberías de una manera fácil y práctica. Accesorio que permite conectar dos tuberías de fluidos en desagües. Longitud de campana: 7 cm.",
    tipo: "Yee",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "0.489.cm",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Tee 4x4 SAL",
    img: "Tee 4x4 SAL Tuboplast.webp",
    img1: "Tee 4x4 SAL Tuboplast.webp",
    img2: "Tee 4x4 SAL Tuboplast.webp",
    img3: "Tee 4x4 SAL Tuboplast.webp",
    descripcion:
      "Realizaras empalmes en las tuberías de una manera fácil y práctica. Accesorio que permite conectar dos tuberías de fluidos en desagües, con una reducción de 2¨. Longitud de campana: 6.5 cm.",
    tipo: "Yee",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "26 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "0.185 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Tee 2x2 SAL",
    img: "Tee 2x2 SAL Tuboplast.webp",
    img1: "Tee 2x2 SAL Tuboplast.webp",
    img2: "Tee 2x2 SAL Tuboplast.webp",
    img3: "Tee 2x2 SAL Tuboplast.webp",
    descripcion:
      "Realizaras empalmes en las tuberías de una manera fácil y práctica. Accesorio que permite conectar dos tuberías de fluidos en desagües. Longitud de campana: 4.5 cm.",
    tipo: "Yee",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "18 cm ",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "0.183 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Yee 2¨ SAL",
    img: "Yee 2 SAL Tuboplast.webp",
    img1: "Yee 2 SAL Tuboplast.webp",
    img2: "Yee 2 SAL Tuboplast.webp",
    img3: "Yee 2 SAL Tuboplast.webp",
    descripcion:
      " El tubo Yee, es un accesorio hecho de PVC ideal para trabajos de gasfitería en el desagüe. Accesorio que permite conectar dos tuberías de fluidos en desagües. Longitud de campana: 4.5 cm.",
    tipo: "union",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "9.5 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "0.035 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },

  {
    name: "Sombrero PVC 4¨",
    img: "Sombrero PVC 4¨.webp",
    img1: "Sombrero PVC 4¨.webp",
    img2: "Sombrero PVC 4¨.webp",
    img3: "Sombrero PVC 4¨.webp",
    descripcion:
      "El sombrero, es un accesorio plástico que evita que los malos olores salgan del tanque. Accesorio que permite conectar dos tuberías de fluidos en desagües. Longitud de campana: 4.2 cm.",
    tipo: "Yee",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "36 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "0.490 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Ramal T de 4 a 2 ",
    img: "Ramal T de 4 a 2 Tuboplast.webp",
    img1: "Ramal T de 4 a 2 Tuboplast.webp",
    img2: "Ramal T de 4 a 2 Tuboplast.webp",
    img3: "Ramal T de 4 a 2 Tuboplast.webp",
    descripcion:
      "Gran capacidad resistente y bajo nivel de corrosión, garantizando un prolongado periodo de utilidad y pureza del agua. Accesorio que permite conectar dos tuberías de fluidos en desagües. Longitud de campana: 4.2 cm.",
    tipo: "Tee",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "17 cm ",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "0.120 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Yee 4¨ SAL",
    img: "Yee 4 SAL Tuboplast.webp",
    img1: "Yee 4 SAL Tuboplast.webp",
    img2: "Yee 4 SAL Tuboplast.webp",
    img3: "Yee 4 SAL Tuboplast.webp",
    descripcion:
      "El tubo Yee, es un accesorio hecho de PVC ideal para trabajos de gasfitería en el desagüe. Accesorio que permite conectar cuatro tuberías de fluidos en desagües. Longitud de campana: 7 cm.",
    tipo: "Tee",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "2.8 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "0.475 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },

  {
    name: "Codo 4x45 SAL",
    img: "Codo 4x45 SAL Tuboplast.webp",
    img1: "Codo 4x45 SAL Tuboplast.webp",
    img2: "Codo 4x45 SAL Tuboplast.webp",
    img3: "Codo 4x45 SAL Tuboplast.webp",
    descripcion:
      "Realiza correctamente las instalaciones de desagüe de tu hogar con este codo elaborado con material de CPVC y gran capacidad de durabilidad; además, es resistente a altas temperaturas, lo cual asegura su prolongado periodo de utilidad. Accesorio que permite tapar el final de una tubería de fluidos en desagües.",
    tipo: "Tapón",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "4.4 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "0.210 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Tee sanitaria 2¨",
    img: "Tee sanitaria 2 Tuboplast.webp",
    img1: "Tee sanitaria 2 Tuboplast.webp",
    img2: "Tee sanitaria 2 Tuboplast.webp",
    img3: "Tee sanitaria 2 Tuboplast.webp",
    descripcion:
      "Realizaras empalmes en las tuberías de una manera fácil y práctica. Tubería para fluidos en desagües. Permite conectar dos tubos de un diámetro mayor a uno menor.",
    tipo: "Reducción",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "14 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "0.135 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Unión 2 SAL ",
    img: "Unión 2 SAL Tuboplast.webp",
    img1: "Unión 2 SAL Tuboplast.webp",
    img2: "Unión 2 SAL Tuboplast.webp",
    img3: "Unión 2 SAL Tuboplast.webp",
    descripcion:
      "Las uniones universales son esenciales para realizar las conexiones de tuberías en tu vivienda. Tubería ideal para fluidos en desagües. Diámetro de campana: 10.52 cm. Longitud de campana: 8.2 cm. Espesor: 0.2 cm.",
    tipo: "Codo",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "23 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "0.133 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Tubo S.Presión 3/4¨",
    img: "Tubo simple presión 3-4.webp",
    img1: "Tubo simple presión 3-4.webp",
    img2: "Tubo simple presión 3-4.webp",
    img3: "Tubo simple presión 3-4.webp",
    descripcion:
      "Sistema de agua para conducción de fluidos a presión. Espesor de 1.8 mm.",
    tipo: "Tuberia",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "1.040kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },

  {
    name: "Tubo roscado 1¨",
    img: "Tubo roscado 1.webp",
    img1: "Tubo roscado 1.webp",
    img2: "Tubo roscado 1.webp",
    img3: "Tubo roscado 1.webp",
    descripcion:
      "Sistema de agua para conducción de fluidos a presión. Espesor nominal de 3.4 mm.",
    tipo: "Tuberia",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Enroscado",
    Peso: "2.261kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Tubo S.Presión 1¨",
    img: "Tubo simple presión 1.webp",
    img1: "Tubo simple presión 1.webp",
    img2: "Tubo simple presión 1.webp",
    img3: "Tubo simple presión 1.webp",
    descripcion:
      "Sistema de agua para conducción de fluidos a presión. Espesor de 1.8 mm.",
    tipo: "Tuberia",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "1. 270kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Tubo roscado 3/4¨",
    img: "Tubo roscado 3-4.webp",
    img1: "Tubo roscado 3-4.webp",
    img2: "Tubo roscado 3-4.webp",
    img3: "Tubo roscado 3-4.webp",
    descripcion:
      "Sistema de agua para conducción de fluidos a presión. Espesor nominal de 2.9 mm.",
    tipo: "Tuberia",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Roscado",
    Peso: "1.613 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Tubo roscado 1/2¨",
    img: "Tubo roscado 1-2.webp",
    img1: "Tubo roscado 1-2.webp",
    img2: "Tubo roscado 1-2.webp",
    img3: "Tubo roscado 1-2.webp",
    descripcion:
      "Sistema de agua para conducción de fluidos a presión. Espesor nominal de 2.9 mm.",
    tipo: "Tuberia",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "1.230kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },

  {
    name: "Curva de agua S.Presión 3/4¨",
    img: "Curva de agua simple presión 3-4.webp",
    img1: "Curva de agua simple presión 3-4.webp",
    img2: "Curva de agua simple presión 3-4.webp",
    img3: "Curva de agua simple presión 3-4.webp",
    descripcion:
      "Tubería para fluidos. Diámetro exterior: 2.65 cm. Espesor: 0.18 cm. Radio de curvatura: 15.1 cm. Longitud de campana: 3.4 cm.",
    tipo: "Curva",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "1.036kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Tee roscado 3/4¨",
    img: "Tee roscado 3-4.webp",
    img1: "Tee roscado 3-4.webp",
    img2: "Tee roscado 3-4.webp",
    img3: "Tee roscado 3-4.webp",
    descripcion:
      "Tubería para fluidos. Diámetro exterior: 2.65 cm. Diámetro de campana: 2.66 cm. Longitud de campana: 3 cm. Espesor: 0.45 cm.",
    tipo: "Tee",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "8 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Enroscado",
    Peso: "1.07 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Curva de agua S.Presión 1¨",
    img: "Curva de agua simple presión 1.webp",
    img1: "Curva de agua simple presión 1.webp",
    img2: "Curva de agua simple presión 1.webp",
    img3: "Curva de agua simple presión 1.webp",
    descripcion:
      "Tubería para fluidos. Diámetro exterior: 3.3 cm. Espesor: 0.18 cm. Radio de curvatura: 18.9 cm. Longitud de campana: 3.4 cm.",
    tipo: "Tuberia",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "1.066 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Codo S.Presión 90° 1¨",
    img: "Codo simple presión 90° 1.webp",
    img1: "Codo simple presión 90° 1.webp",
    img2: "Codo simple presión 90° 1.webp",
    img3: "Codo simple presión 90° 1.webp",
    descripcion:
      "Tubería para fluidos. Diámetro exterior: 3.3 cm. Diámetro de campana: 3.32 cm. Longitud de campana: 3.8 cm. Espesor: 0.55 cm.",
    tipo: "codo",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "6 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "1.08kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },

  {
    name: "Adaptador roscado UPR 3/4¨",
    img: "Adaptador roscado UPR 3-4.webp",
    img1: "Adaptador roscado UPR 3-4.webp",
    img2: "Adaptador roscado UPR 3-4.webp",
    img3: "Adaptador roscado UPR 3-4.webp",
    descripcion:
      "Tubería ideal para fluidos. Diámetro de campana: 4.5 cm. Longitud de rosca: 2.1 cm. Espesor: 0.5 cm.",
    tipo: "Adaptador",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "37 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Enroscado",
    Diámetronominal: "1.9 cm",
    Peso: "0.02 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Codo roscado 90° 3/4¨",
    img: "Codo roscado 90° 3-4.webp",
    img1: "Codo roscado 90° 3-4.webp",
    img2: "Codo roscado 90° 3-4.webp",
    img3: "Codo roscado 90° 3-4.webp",
    descripcion:
      "Tubería para fluidos. Diámetro exterior: 2.65 cm. Diámetro de campana: 2.67 cm. Longitud de campana: 2.8 cm. Espesor: 0.45 cm.",
    tipo: "codo",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "5 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Enroscado",
    Diámetronominal: "1.9 cm",
    Peso: "0.05 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Unión roscado 3/4¨",
    img: "Unión roscado 3-4.webp",
    img1: "Unión roscado 3-4.webp",
    img2: "Unión roscado 3-4.webp",
    img3: "Unión roscado 3-4.webp",
    descripcion:
      "Ideal para uniones entre tuberías de fluidos. Diámetro de campana: 2.67 cm. Longitud de campana: 2.4 cm. Espesor: 0.45 cm.",
    tipo: "Unión",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "5.5 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Enroscado",
    Peso: "0.02 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Tee S. presión 3/4¨",
    img: "Tee simple presión 3-4.webp",
    img1: "Tee simple presión 3-4.webp",
    img2: "Tee simple presión 3-4.webp",
    img3: "Tee simple presión 3-4.webp",
    descripcion:
      "Tubería para fluidos. Diámetro exterior: 2.65 cm. Diámetro de campana: 2.66 cm. Longitud de campana: 3 cm. Espesor: 0.45 cm.",
    tipo: "Tee",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "8 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Peso: "0.07kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },

  {
    name: "Codo roscado 90° 1¨",
    img: "Codo roscado 90 1.webp",
    img1: "Codo roscado 90 1.webp",
    img2: "Codo roscado 90 1.webp",
    img3: "Codo roscado 90 1.webp",
    descripcion:
      "Tubería para fluidos. Diámetro exterior: 3.3 cm. Diámetro de campana: 3.32 cm. Longitud de campana: 3.8 cm. Espesor: 0.55 cm.",
    tipo: "Codo",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "6 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Enroscado",
    Diámetronominal: "2.54 cm",
    Peso: "0.08 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Tapón hembra simple presión 1/2¨",
    img: "Tapón hembra simple presión 1-2.webp",
    img1: "Tapón hembra simple presión 1-2.webp",
    img2: "Tapón hembra simple presión 1-2.webp",
    img3: "Tapón hembra simple presión 1-2.webp",
    descripcion:
      "Tubería para fluidos. Diámetro de campana: 4.5 cm. Longitud de rosca: 2.1 cm. Espesor: 0.5 cm.",
    tipo: "Tapón",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "8 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Diámetronominal: "1.27 cm",
    Peso: "0.01 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Unión roscado 1¨",
    img: "Unión roscado 1.webp",
    img1: "Unión roscado 1.webp",
    img2: "Unión roscado 1.webp",
    img3: "Unión roscado 1.webp",
    descripcion: "Ideal para uniones entre tuberías de fluidos.",
    tipo: "Unión",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "8 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Enroscado",
    Diámetronominal: "2.54 cm",
    Peso: "0.065 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Codo simple presión 45° 1¨",
    img: "Codo simple presión 45 1.webp",
    img1: "Codo simple presión 45 1.webp",
    img2: "Codo simple presión 45 1.webp",
    img3: "Codo simple presión 45 1.webp",
    descripcion:
      "Tubería para fluidos. Diámetro exterior: 3.3 cm. Diámetro de campana: 3.31 cm. Longitud de campana: 4.8 cm. Espesor: 0.18 cm.",
    tipo: "Codo",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "8 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Diámetronominal: "2.54 cm",
    Peso: "0.05 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },

  {
    name: "Curva de agua simple presión 1/2¨",
    img: "Curva de agua simple presión 1-2.webp",
    img1: "Curva de agua simple presión 1-2.webp",
    img2: "Curva de agua simple presión 1-2.webp",
    img3: "Curva de agua simple presión 1-2.webp",
    descripcion:
      "Tubería para fluidos. Diámetro exterior: 2.1 cm. Espesor: 0.18 cm. Radio de curvatura: 12 cm. Longitud de campana: 3.2 cm.",
    tipo: "Curva",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "8 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Diámetronominal: "1.27 cm",
    Peso: "0.036 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Unión simple presión 1¨",
    img: "Unión simple presión 1.webp",
    img1: "Unión simple presión 1.webp",
    img2: "Unión simple presión 1.webp",
    img3: "Unión simple presión 1.webp",
    descripcion:
      "Ideal para uniones entre tuberías de fluidos. Diámetro de campana: 3.32 cm. Longitud de campana: 3.2 cm. Espesor: 0.5 cm.",
    tipo: "Unión",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "6 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Diámetronominal: "2.54 cm",
    Peso: "0.065 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Tapón hembra simple presión 1¨",
    img: "Tapón hembra simple presión 1.webp",
    img1: "Tapón hembra simple presión 1.webp",
    img2: "Tapón hembra simple presión 1.webp",
    img3: "Tapón hembra simple presión 1.webp",
    descripcion:
      "Tubería para fluidos. Diámetro de campana: 4.5 cm. Longitud de rosca: 2.1 cm. Espesor: 0.5 cm.",
    tipo: "Tapón",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "3.7 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Enroscado",
    Diámetronominal: "2.54 cm",
    Peso: "0.02 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Codo simple presión 90° 1/2¨",
    img: "Codo simple presión 90° 1-2.webp",
    img1: "Codo simple presión 90° 1-2.webp",
    img2: "Codo simple presión 90° 1-2.webp",
    img3: "Codo simple presión 90° 1-2.webp",
    descripcion:
      "Tubería para fluidos. Diámetro exterior: 2.1 cm. Diámetro de campana: 2.12 cm. Longitud de campana: 2 cm. Espesor: 0.45 cm.",
    tipo: "Codo",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "8 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Diámetronominal: "1.27 cm",
    Peso: "0.03 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },

  {
    name: "Tee simple presión 1/2¨",
    img: "Tee simple presión 1-2.webp",
    img1: "Tee simple presión 1-2.webp",
    img2: "Tee simple presión 1-2.webp",
    img3: "Tee simple presión 1-2.webp",
    descripcion:
      "Tubería para fluidos. Diámetro exterior: 2.1 cm. Diámetro de campana: 2.12 cm. Longitud de campana: 2.5 cm. Espesor: 0.45 cm.",
    tipo: "Tee",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "7 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Diámetronominal: "1.27 cm",
    Peso: "0.05 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Tee roscado 1¨",
    img: "Tee roscado 1.webp",
    img1: "Tee roscado 1.webp",
    img2: "Tee roscado 1.webp",
    img3: "Tee roscado 1.webp",
    descripcion:
      "Tubería para fluidos. Diámetro exterior: 3.3 cm. Diámetro de campana: 3.32 cm. Longitud de campana: 4.8 cm. Espesor: 0.55 cm.",
    tipo: "Tee",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "12 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Enroscado",
    Diámetronominal: "2.54 cm",
    Peso: "0.01 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Adaptador UPR roscado 1¨",
    img: "Adaptador UPR roscado 1.webp",
    img1: "Adaptador UPR roscado 1.webp",
    img2: "Adaptador UPR roscado 1.webp",
    img3: "Adaptador UPR roscado 1.webp",
    descripcion:
      "Tubería ideal para fluidos. Diámetro de campana: 4.5 cm. Longitud de rosca: 2.1 cm. Espesor: 0.5 cm.",
    tipo: "Adaptador",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "37 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Diámetronominal: "2.54 cm",
    Peso: "0.03 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Codo simple presión 45° 3/4¨",
    img: "Codo simple presión 45° 3-4.webp",
    img1: "Codo simple presión 45° 3-4.webp",
    img2: "Codo simple presión 45° 3-4.webp",
    img3: "Codo simple presión 45° 3-4.webp",
    descripcion:
      "Tubería para fluidos. Diámetro exterior: 2.65 cm. Diámetro de campana: 2.6 cm. Longitud de campana: 3.5 cm. Espesor: 0.18 cm.",
    tipo: "Codo",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "6 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Diámetronominal: "1.9 cm",
    Peso: "0.05 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },

  {
    name: "Unión simple presión 3/4¨",
    img: "Unión simple presión 3-4.webp",
    img1: "Unión simple presión 3-4.webp",
    img2: "Unión simple presión 3-4.webp",
    img3: "Unión simple presión 3-4.webp",
    descripcion:
      "Ideal para uniones entre tuberías de fluidos. Diámetro de campana: 2.67 cm. Longitud de campana: 2.9 cm. Espesor: 0.5 cm.",
    tipo: "Unión",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "6 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Diámetronominal: "1.9 cm",
    Peso: "0.06 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Tapón macho simple presión 3/4¨",
    img: "Tapón macho simple presión 3-4.webp",
    img1: "Tapón macho simple presión 3-4.webp",
    img2: "Tapón macho simple presión 3-4.webp",
    img3: "Tapón macho simple presión 3-4.webp",
    descripcion:
      "Tubería para fluidos. Diámetro de campana: 2.65 cm. Longitud de espiga: 1.7 cm. Espesor: 0.18 cm.",
    tipo: "Tapón",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "3.3 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Diámetronominal: "1.9 cm",
    Peso: "0.01 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Tapón hembra simple presión 3/4¨",
    img: "Tapón hembra simple presión 3-4.webp",
    img1: "Tapón hembra simple presión 3-4.webp",
    img2: "Tapón hembra simple presión 3-4.webp",
    img3: "Tapón hembra simple presión 3-4.webp",
    descripcion:
      "Tubería para fluidos. Diámetro de campana: 4.5 cm. Longitud de rosca: 2.1 cm. Espesor: 0.5 cm.",
    tipo: "Tapón",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "3.7 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Enroscado",
    Diámetronominal: "1.9 cm",
    Peso: "0.02 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Unión simple presión 1/2¨",
    img: "Unión simple presión 1-2.webp",
    img1: "Unión simple presión 1-2.webp",
    img2: "Unión simple presión 1-2.webp",
    img3: "Unión simple presión 1-2.webp",
    descripcion:
      "Tubería para fluidos. Diámetro de campana: 2.12 cm. Longitud de campana: 2.5 cm. Espesor: 0.45 cm.",
    tipo: "Unión",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "5.5 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Diámetronominal: "1.27 cm",
    Peso: "0.02 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },

  {
    name: "Codo simple presión 90° 3/4¨",
    img: "Codo simple presión 90° 3-4.webp",
    img1: "Codo simple presión 90° 3-4.webp",
    img2: "Codo simple presión 90° 3-4.webp",
    img3: "Codo simple presión 90° 3-4.webp",
    descripcion:
      "Tubería para fluidos. Diámetro exterior: 2.65 cm. Diámetro de campana: 2.67 cm. Longitud de campana: 2.8 cm. Espesor: 0.45 cm.",
    tipo: "Codo",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "5 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Diámetronominal: "1.9 cm",
    Peso: "0.05 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Tapón macho simple presión 1/2¨",
    img: "Tapón macho simple presión 1-2.webp",
    img1: "Tapón macho simple presión 1-2.webp",
    img2: "Tapón macho simple presión 1-2.webp",
    img3: "Tapón macho simple presión 1-2.webp",
    descripcion:
      "Tubería para fluidos. Diámetro de campana: 2.1 cm. Longitud de espiga: 2.4 cm. Espesor: 0.18 cm.",
    tipo: "Tapón",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "3 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Diámetronominal: "1.27 cm",
    Peso: "0.01 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Unión roscado 1/2¨",
    img: "Unión roscado 1-2.webp",
    img1: "Unión roscado 1-2.webp",
    img2: "Unión roscado 1-2.webp",
    img3: "Unión roscado 1-2.webp",
    descripcion:
      "Ideal para uniones entre tuberías de fluidos. Diámetro de campana: 2.12 cm. Longitud de campana: 2 cm. Espesor: 0.45 cm.",
    tipo: "Unión",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "4.5 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Enroscado",
    Diámetronominal: "1.27 cm",
    Peso: "0.05 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Tee simple presión 1¨",
    img: "Tee simple presión 1.webp",
    img1: "Tee simple presión 1.webp",
    img2: "Tee simple presión 1.webp",
    img3: "Tee simple presión 1.webp",
    descripcion:
      "Tubería para fluidos. Diámetro exterior: 3.3 cm. Diámetro de campana: 3.32 cm. Longitud de campana: 4.8 cm. Espesor: 0.55 cm.",
    tipo: "Tee",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "12 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Diámetronominal: "2.54 cm",
    Peso: "0.1 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },

  {
    name: "Unión SEL Tuboplast 5/8¨",
    img: "Unión SEL Tuboplast 5-8.webp",
    img1: "Unión SEL Tuboplast 5-8.webp",
    img2: "Unión SEL Tuboplast 5-8.webp",
    img3: "Unión SEL Tuboplast 5-8.webp",
    descripcion:
      "Espesor: 1.1 mm. Sistema de empalme por simple presión. Resistencia a la tracción: 400-560 kgf/cm2. Resistente a aplastamientos, no presenta grietas ni roturas. Longitud de campana: 1.8 cm.",
    tipo: "Codo",
    marca: "Tuboplast",
    ancho: "1.58 cm",
    profundidad: "1.58 cm",
    alto: "4 cm",
    material: "PVC-U",
    Tipodeconexión: "",
    Diámetronominal: "",
    Peso: "0.005 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },

  {
    name: "Conector SEL Tuboplast 5/8¨",
    img: "Conector SEL Tuboplast 5-8.webp",
    img1: "Conector SEL Tuboplast 5-8.webp",
    img2: "Conector SEL Tuboplast 5-8.webp",
    img3:
      "ConectorDiámetro nominal: 1.59 cm. Espesor: 0.11 cm. Longitud de campana: 1.6 cm. Sistema de empalme por simple presión. Resistencia a la tracción: 400-560 kgf/cm2. Resistente a aplastamientos, no presenta grietas ni roturas.",
    tipo: "Conector",
    marca: "Tuboplast",
    ancho: "1.59 cm",
    profundidad: "1.59 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "",
    Diámetronominal: "",
    Peso: "0.002 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },

  {
    name: "Curva SEL Tuboplast 5/8¨",
    img: "Curva SEL Tuboplast 5-8.webp",
    img1: "Curva SEL Tuboplast 5-8.webp",
    img2: "Curva SEL Tuboplast 5-8.webp",
    img3: "Curva SEL Tuboplast 5-8.webp",
    descripcion:
      "Radio de curvatura: 9 cm. Espesor: 0.11 cm. Longitud de campana: 1.5 cm. Sistema de empalme por simple presión. Resistencia a la tracción: 400-560 kgf/cm2. Resistente a aplastamientos, no presenta grietas ni roturas.",
    tipo: "Curva",
    marca: "Tuboplast",
    ancho: "1.59 cm",
    profundidad: "1.59 cm",
    alto: "1.6 cm",
    material: "PVC-U",
    Tipodeconexión: "",
    Diámetronominal: "",
    Peso: "0.012 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },

  {
    name: "Conector SAP Tuboplast 5/8¨",
    img: "Conector SAP Tuboplast 5-8.webp",
    img1: "Conector SAP Tuboplast 5-8.webp",
    img2: "Conector SAP Tuboplast 5-8.webp",
    img3: "Conector SAP Tuboplast 5-8.webp",
    descripcion:
      "Diámetro nominal: 1.27 cm. Espesor: 0.18 cm. Longitud de espiga: 2.15 cm. Sistema de empalme por simple presión. Resistencia a la tracción: 400-560 kgf/cm2. Resistente a aplastamientos, no presenta grietas ni roturas.",
    tipo: "Conector",
    marca: "Tuboplast",
    ancho: "2.1 cm",
    profundidad: "2.1 cm",
    alto: "2.2 cm",
    material: "PVC-U",
    Tipodeconexión: "",
    Diámetronominal: "",
    Peso: "0.005 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },

  {
    name: "Unión SAP Tuboplast 1/2¨",
    img: "Unión SAP Tuboplast 1-2.webp",
    img1: "Unión SAP Tuboplast 1-2.webp",
    img2: "Unión SAP Tuboplast 1-2.webp",
    img3: "Unión SAP Tuboplast 1-2.webp",
    descripcion:
      "Espesor: 1.3 mm. Sistema de empalme por simple presión. Resistencia a la tracción: 400-560 kgf/cm2. Resistente a aplastamientos, no presenta grietas ni roturas. Longitud de campana: 2.8 cm.",
    tipo: "Unión",
    marca: "Tuboplast",
    ancho: "1.27 cm",
    profundidad: "6 cm",
    alto: "6 cm",
    material: "PVC-U",
    Tipodeconexión: "",
    Diámetronominal: "",
    Peso: "0.005 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },

  {
    name: "Codo simple presión 45° 1/2¨",
    img: "Codo simple presión 45° 1-2.webp",
    img1: "Codo simple presión 45° 1-2.webp",
    img2: "Codo simple presión 45° 1-2.webp",
    img3: "Codo simple presión 45° 1-2.webp",
    descripcion:
      "Tubería para fluidos. Diámetro exterior: 2.1 cm. Diámetro de campana: 2.12 cm. Longitud de campana: 3 cm. Espesor: 0.18 cm.",
    tipo: "Codo",
    marca: "Tuboplast",
    ancho: "",
    profundidad: "5 cm",
    alto: "",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Diámetronominal: "1.27 cm",
    Peso: "0.03 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },

  {
    name: "Unión SAP Tuboplast 1¨",
    img: "Unión SAP Tuboplast 1.webp",
    img1: "Unión SAP Tuboplast 1.webp",
    img2: "Unión SAP Tuboplast 1.webp",
    img3: "Unión SAP Tuboplast 1.webp",
    descripcion:
      "Espesor: 1.3 mm. Sistema de empalme por simple presión. Resistencia a la tracción: 400-560 kgf/cm2. Resistente a aplastamientos, no presenta grietas ni roturas. Longitud de campana: 2.8 cm.",
    tipo: "Unión",
    marca: "Tuboplast",
    ancho: "2c54 cm",
    profundidad: "2.54 cm",
    alto: "4 cm",
    material: "PVC-U",
    Tipodeconexión: "Presión",
    Diámetronominal: "",
    Peso: "0.005 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Unión SEL Tuboplast 1¨",
    img: "Unión SEL Tuboplast 1.webp",
    img1: "Unión SEL Tuboplast 1.webp",
    img2: "Unión SEL Tuboplast 1.webp",
    img3: "Unión SEL Tuboplast 1.webp",
    descripcion:
      "Espesor: 1.3 mm. Sistema de empalme por simple presión. Resistencia a la tracción: 400-560 kgf/cm2. Resistente a aplastamientos, no presenta grietas ni roturas. Longitud de campana: 2.8 cm.",
    tipo: "Unión",
    marca: "Tuboplast",
    ancho: "2.54 cm",
    profundidad: "2.54 cm",
    alto: "4 cm",
    material: "PVC-U",
    Tipodeconexión: "",
    Diámetronominal: "",
    Peso: "0.005 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Conector SAP Tuboplast 1¨",
    img: "Conector SAP Tuboplast 1.webp",
    img1: "Conector SAP Tuboplast 1.webp",
    img2: "Conector SAP Tuboplast 1.webp",
    img3: "Conector SAP Tuboplast 1.webp",
    descripcion:
      "Diámetro nominal: 2.54 cm. Espesor: 0.18 cm. Longitud de campana: 3.25 cm. Sistema de empalme por simple presión. Resistencia a la tracción: 400-560 kgf/cm2. Resistente a aplastamientos, no presenta grietas ni roturas.",
    tipo: "Conector",
    marca: "Tuboplast",
    ancho: "3.3 cm",
    profundidad: "3.3 cm",
    alto: "3.4 cm",
    material: "PVC-U",
    Tipodeconexión: "",
    Diámetronominal: "",
    Peso: "0.01 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Curva SEL Tuboplast 1¨",
    img: "Curva SEL Tuboplast 1.webp",
    img1: "Curva SEL Tuboplast 1.webp",
    img2: "Curva SEL Tuboplast 1.webp",
    img3: "Curva SEL Tuboplast 1.webp",
    descripcion:
      "Radio de curvatura: 14.5 cm. Espesor: 0.13 cm. Longitud de campana: 2.5 cm. Sistema de empalme por simple presión. Resistencia a la tracción: 400-560 kgf/cm2. Resistente a aplastamientos, no presenta grietas ni roturas.",
    tipo: "Curva",
    marca: "Tuboplast",
    ancho: "2.54 cm",
    profundidad: "2.54 cm",
    alto: "2.5 cm",
    material: "PVC-U",
    Tipodeconexión: "",
    Diámetronominal: "",
    Peso: "0.031 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
  {
    name: "Conector SEL Tuboplast 1¨",
    img: "Conector SEL Tuboplast 1.webp",
    img1: "Conector SEL Tuboplast 1.webp",
    img2: "Conector SEL Tuboplast 1.webp",
    img3: "Conector SEL Tuboplast 1.webp",
    descripcion:
      "Diámetro nominal: 2.54 cm. Espesor: 0.13 cm. Longitud de espiga: 2.45 cm. Sistema de empalme por simple presión. Resistencia a la tracción: 400-560 kgf/cm2. Resistente a aplastamientos, no presenta grietas ni roturas.",
    tipo: "Conector",
    marca: "Tuboplast",
    ancho: "2.54 cm",
    profundidad: "2.54 cm",
    alto: "2.5 cm",
    material: "PVC-U",
    Tipodeconexión: "",
    Diámetronominal: "",
    Peso: "0.005 kg",
    precio: "0",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Accesorios y conexiones",
  },
];
