export default [
  {
    name:"Codo CPVC 3/4'' 90°", 
    img: "308617.jfif",
    img1:"308617.jfif",
    img2:"308617.jfif",
    img3:"308617.jfif",
    descripcion: "Conexión de CPVC están diseñadas para trabajar en forma continua a una presión hidrostática y a temperaturas exigentes.", 
    usos: "",
    Recomendaciones: "Para asegurar la instalación utilizar soldadura de CPVC PAVCO en la conexión de tipo embone o teflón en la conexión tipo rosca.",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "3/4''",
    presion:"100 psi (6.89 bar o 6.8 bar)",
    Color: "Gris",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo CPVC 3/4'' 45°", 
    img: "308595 (1).jfif",
    img1:"308595 (1).jfif",
    img2:"308595 (1).jfif",
    img3:"308595 (1).jfif",
    descripcion: "Conexión de CPVC están diseñadas para trabajar en forma continua a una presión hidrostática y a temperaturas exigentes.", 
    usos: "Para agua caliente",
    Recomendaciones: "sUsar soldadura de CPVC PAVCO para asegurar las uniones. Tener cuidado en la carga, transporte y descarga del material.",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "3/4''",
    presion:"100 psi (6.89 bar o 6.8 bar)",
    Color: "Gris",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo Desagüe PVC 2'' x 45°", 
    img: "344877.jfif",
    img1:"344877.jfif",
    img2:"344877.jfif",
    img3:"344877.jfif",
    descripcion: "Codo de desagüe de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
    usos: "Para desagüe",
    Recomendaciones: "Usar soldadura de PVC PAVCO para asegurar las uniones. Tener cuidado en la carga, transporte y descarga del material.",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "2''",
    presion:"890 psi",
    Color: "Gris orgánico",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo CPVC 1/2'' 45°", 
    img: "308587.jfif",
    img1:"308587.jfif",
    img2:"308587.jfif",
    img3:"308587.jfif",
    descripcion: "Conexión de CPVC están diseñadas para trabajar en forma continua a una presión hidrostática y a temperaturas exigentes.", 
    usos: "Para agua caliente",
    Recomendaciones: "Usar soldadura de CPVC PAVCO para asegurar las uniones. Tener cuidado en la carga, transporte y descarga del material.",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "1/2''",
    presion:"100 psi (6.89 bar o 6.8 bar)",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },

  {
    name:"Codo PVC 45° SP 1 1/2''", 
    img: "2310449.jfif",
    img1:"2310449.jfif",
    img2:"2310449.jfif",
    img3:"2310449.jfif",
    descripcion: "Codo PVC de 45° sp con medidas 1 1/2''", 
    usos: "Para desagües",
    Recomendaciones: "Usar soldadura de PVC PAVCO para asegurar las uniones. Tener cuidado en la carga, transporte y descarga del material.",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "1 1/2''",
    presion:"",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo Desagüe PVC 4'' x 90°", 
    img: "34494X.jfif",
    img1:"34494X.jfif",
    img2:"34494X.jfif",
    img3:"34494X.jfif",
    descripcion: "Codo de desagüe de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
    usos: "Para desagüe",
    Recomendaciones: "Usar soldadura de PVC PAVCO para asegurar las uniones. Tener cuidado en la carga, transporte y descarga del material.",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "4''",
    presion:"710 psi",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo Desagüe PVC 4'' x 45°", 
    img: "344893.jfif",
    img1:"344893.jfif",
    img2:"344893.jfif",
    img3:"344893.jfif",
    descripcion: "Codo de desagüe de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
    usos: "Para desagüe",
    Recomendaciones: "Usar soldadura de PVC PAVCO para asegurar las uniones. Tener cuidado en la carga, transporte y descarga del material.",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "4''",
    presion:"710 psi",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo Desagüe PVC 1 1/2'' x 45°", 
    img: "344869.jfif",
    img1:"344869.jfif",
    img2:"344869.jfif",
    img3:"344869.jfif",
    descripcion: "Codo de desagüe de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
    usos: "Para desagüe",
    Recomendaciones: "",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "1 1/2''",
    presion:"1060 psi",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo Desagüe 6'' x 90°", 
    img: "391921.jfif",
    img1:"391921.jfif",
    img2:"391921.jfif",
    img3:"391921.jfif",
    descripcion: "Codo de desagüe de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
    usos: "Para desagüe",
    Recomendaciones: "",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "6''",
    presion:"560 psi",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo PVC-P sp 2'' 90°", 
    img: "396346.jfif",
    img1:"396346.jfif",
    img2:"396346.jfif",
    img3:"396346.jfif",
    descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
    usos: "Para agua fría",
    Recomendaciones: "",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "2''",
    presion:"10 bar (145 psi)",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo PVC-P sp 3/4'' 45°", 
    img: "308951.jfif",
    img1:"308951.jfif",
    img2:"308951.jfif",
    img3:"308951.jfif",
    descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
    usos: "Para agua fría",
    Recomendaciones: "",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "3/4''",
    presion:"10 bar (145 psi)",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo PVC 45° SAL 3''", 
    img: "344885.jfif",
    img1:"344885.jfif",
    img2:"344885.jfif",
    img3:"344885.jfif",
    descripcion: "Codo de desagüe de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
    usos: "Para desagüe",
    Recomendaciones: "",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "3''",
    presion:"",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo PVC-P sp 1'' 90°", 
    img: "308978.jfif",
    img1:"308978.jfif",
    img2:"308978.jfif",
    img3:"308978.jfif",
    descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
    usos: "Para agua fría",
    Recomendaciones: "",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "1''",
    presion:"10 bar (145 psi)",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo PVC-P c/r 1 1/4'' 90°", 
    img: "309389.jfif",
    img1:"309389.jfif",
    img2:"309389.jfif",
    img3:"309389.jfif",
    descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
    usos: "Para agua fría",
    Recomendaciones: "",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "1 1/4''",
    presion:"10 bar (145 psi)",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo PVC-P c/r 1'' 90°", 
    img: "309397.jfif",
    img1:"309397.jfif",
    img2:"309397.jfif",
    img3:"309397.jfif",
    descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
    usos: "Para agua fría",
    Recomendaciones: "",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "1''",
    presion:"10 bar (145 psi)",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo PVC-P c/r 1'' 90°", 
    img: "309397 (1).jfif",
    img1:"309397 (1).jfif",
    img2:"309397 (1).jfif",
    img3:"309397 (1).jfif",
    descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
    usos: "Para agua fría",
    Recomendaciones: "",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "1''",
    presion:"10 bar (145 psi)",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo Desagüe 1 1/4'' x 45°", 
    img: "2310457.jfif",
    img1:"2310457.jfif",
    img2:"2310457.jfif",
    img3:"2310457.jfif",
    descripcion: "Codo de desagüe de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
    usos: "Para desagüe",
    Recomendaciones: "",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "1 1/4''",
    presion:"560 psi",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo PVC-P c/r 3/4'' 90°", 
    img: "309419.jfif",
    img1:"309419.jfif",
    img2:"309419.jfif",
    img3:"309419.jfif",
    descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
    usos: "Para agua fría",
    Recomendaciones: "",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "3/4''",
    presion:"10 bar (145 psi)",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo PVC-P sp 1 1/2'' 90°", 
    img: "396427.jfif",
    img1:"396427.jfif",
    img2:"396427.jfif",
    img3:"396427.jfif",
    descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
    usos: "Para agua fría",
    Recomendaciones: "",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "1 1/2''",
    presion:"10 bar (145 psi)",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo Desagüe PVC 2'' x 90°", 
    img: "344923.jfif",
    img1:"344923.jfif",
    img2:"344923.jfif",
    img3:"344923.jfif",
    descripcion: "Codo de desagüe de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
    usos: "Para desagüe",
    Recomendaciones: "",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: " 2''",
    presion:"890 psi",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo PVC-P sp 1 1/4'' 90°", 
    img: "30896X.jfif",
    img1:"30896X.jfif",
    img2:"30896X.jfif",
    img3:"30896X.jfif",
    descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
    usos: "Para agua fría",
    Recomendaciones: "",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "1 1/4'' ",
    presion:"10 bar (145 psi)",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo CPVC 1/2'' 90°", 
    img: "308609.jfif",
    img1:"308609.jfif",
    img2:"308609.jfif",
    img3:"308609.jfif",
    descripcion: "Conexión de CPVC están diseñadas para trabajar en forma continua a una presión hidrostática y a temperaturas exigentes.", 
    usos: "Para agua caliente",
    Recomendaciones: "",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "1/2''",
    presion:"100 psi (6.89 bar o 6.8 bar)",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo cachimba PVC 1/2'' 90°", 
    img: "309354.jfif",
    img1:"309354.jfif",
    img2:"309354.jfif",
    img3:"309354.jfif",
    descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
    usos: "Para agua fría",
    Recomendaciones: "",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "1/2''",
    presion:"10 bar (145 psi)",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo PVC-P sp 3/4'' 90°", 
    img: "308994.jfif",
    img1:"308994.jfif",
    img2:"308994.jfif",
    img3:"308994.jfif",
    descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
    usos: "Para agua fría",
    Recomendaciones: "",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "3/4''",
    presion:"10 bar (145 psi)",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo PVC 45° 1/2'' SP", 
    img: "308943.jfif",
    img1:"308943.jfif",
    img2:"308943.jfif",
    img3:"308943.jfif",
    descripcion: "Codo de desagüe de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
    usos: "Para agua fría",
    Recomendaciones: "",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "",
    presion:"",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo Desagüe 3'' x 45°", 
    img: "2680890.jfif",
    img1:"2680890.jfif",
    img2:"2680890.jfif",
    img3:"2680890.jfif",
    descripcion: "Codo de desagüe de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
    usos: "Para desagüe",
    Recomendaciones: "",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "3''",
    presion:"560 psi",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo PVC-P sp 1'' 45°", 
    img: "308935.jfif",
    img1:"308935.jfif",
    img2:"308935.jfif",
    img3:"308935.jfif",
    descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
    usos: "Para agua fría",
    Recomendaciones: "",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "1''",
    presion:"10 bar (145 psi)",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
  {
    name:"Codo PVC-P c/r 1 1/2'' 90°", 
    img: "309370.jfif",
    img1:"309370.jfif",
    img2:"309370.jfif",
    img3:"309370.jfif",
    descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
    usos: "Para agua fría",
    Recomendaciones: "",  
    tipo: "Codo",
    marca: "Pavco",
    material: "PVC",
    Medida: "1 1/2''",
    presion:"10 bar (145 psi)",
    Color: "",
    cantidad: "",
    procedencia:"Nacional",
    precio: "",
    precioantes: "0",
    oferta: "0 %",
    categoriageneral: "Gasfiteria",
    categoria: "Conexiones Para Agua"
  },
];

