export default [
    {
      name:"Codo CPVC 3/4'' 90°", 
      img: "308617.jfif",
      img1:"308617.jfif",
      img2:"308617.jfif",
      img3:"308617.jfif",
      descripcion: "Conexión de CPVC están diseñadas para trabajar en forma continua a una presión hidrostática y a temperaturas exigentes.", 
      usos: "",
      Recomendaciones: "Para asegurar la instalación utilizar soldadura de CPVC PAVCO en la conexión de tipo embone o teflón en la conexión tipo rosca.",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "3/4''",
      presion:"100 psi (6.89 bar o 6.8 bar)",
      Color: "Gris",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo CPVC 3/4'' 45°", 
      img: "308595 (1).jfif",
      img1:"308595 (1).jfif",
      img2:"308595 (1).jfif",
      img3:"308595 (1).jfif",
      descripcion: "Conexión de CPVC están diseñadas para trabajar en forma continua a una presión hidrostática y a temperaturas exigentes.", 
      usos: "Para agua caliente",
      Recomendaciones: "sUsar soldadura de CPVC PAVCO para asegurar las uniones. Tener cuidado en la carga, transporte y descarga del material.",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "3/4''",
      presion:"100 psi (6.89 bar o 6.8 bar)",
      Color: "Gris",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo Desagüe PVC 2'' x 45°", 
      img: "344877.jfif",
      img1:"344877.jfif",
      img2:"344877.jfif",
      img3:"344877.jfif",
      descripcion: "Codo de desagüe de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
      usos: "Para desagüe",
      Recomendaciones: "Usar soldadura de PVC PAVCO para asegurar las uniones. Tener cuidado en la carga, transporte y descarga del material.",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "2''",
      presion:"890 psi",
      Color: "Gris orgánico",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo CPVC 1/2'' 45°", 
      img: "308587.jfif",
      img1:"308587.jfif",
      img2:"308587.jfif",
      img3:"308587.jfif",
      descripcion: "Conexión de CPVC están diseñadas para trabajar en forma continua a una presión hidrostática y a temperaturas exigentes.", 
      usos: "Para agua caliente",
      Recomendaciones: "Usar soldadura de CPVC PAVCO para asegurar las uniones. Tener cuidado en la carga, transporte y descarga del material.",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "1/2''",
      presion:"100 psi (6.89 bar o 6.8 bar)",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
  
    {
      name:"Codo PVC 45° SP 1 1/2''", 
      img: "2310449.jfif",
      img1:"2310449.jfif",
      img2:"2310449.jfif",
      img3:"2310449.jfif",
      descripcion: "Codo PVC de 45° sp con medidas 1 1/2''", 
      usos: "Para desagües",
      Recomendaciones: "Usar soldadura de PVC PAVCO para asegurar las uniones. Tener cuidado en la carga, transporte y descarga del material.",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "1 1/2''",
      presion:"",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo Desagüe PVC 4'' x 90°", 
      img: "34494X.jfif",
      img1:"34494X.jfif",
      img2:"34494X.jfif",
      img3:"34494X.jfif",
      descripcion: "Codo de desagüe de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
      usos: "Para desagüe",
      Recomendaciones: "Usar soldadura de PVC PAVCO para asegurar las uniones. Tener cuidado en la carga, transporte y descarga del material.",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "4''",
      presion:"710 psi",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo Desagüe PVC 4'' x 45°", 
      img: "344893.jfif",
      img1:"344893.jfif",
      img2:"344893.jfif",
      img3:"344893.jfif",
      descripcion: "Codo de desagüe de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
      usos: "Para desagüe",
      Recomendaciones: "Usar soldadura de PVC PAVCO para asegurar las uniones. Tener cuidado en la carga, transporte y descarga del material.",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "4''",
      presion:"710 psi",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo Desagüe PVC 1 1/2'' x 45°", 
      img: "344869.jfif",
      img1:"344869.jfif",
      img2:"344869.jfif",
      img3:"344869.jfif",
      descripcion: "Codo de desagüe de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
      usos: "Para desagüe",
      Recomendaciones: "",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "1 1/2''",
      presion:"1060 psi",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo Desagüe 6'' x 90°", 
      img: "391921.jfif",
      img1:"391921.jfif",
      img2:"391921.jfif",
      img3:"391921.jfif",
      descripcion: "Codo de desagüe de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
      usos: "Para desagüe",
      Recomendaciones: "",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "6''",
      presion:"560 psi",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo PVC-P sp 2'' 90°", 
      img: "396346.jfif",
      img1:"396346.jfif",
      img2:"396346.jfif",
      img3:"396346.jfif",
      descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
      usos: "Para agua fría",
      Recomendaciones: "",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "2''",
      presion:"10 bar (145 psi)",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo PVC-P sp 3/4'' 45°", 
      img: "308951.jfif",
      img1:"308951.jfif",
      img2:"308951.jfif",
      img3:"308951.jfif",
      descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
      usos: "Para agua fría",
      Recomendaciones: "",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "3/4''",
      presion:"10 bar (145 psi)",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo PVC 45° SAL 3''", 
      img: "344885.jfif",
      img1:"344885.jfif",
      img2:"344885.jfif",
      img3:"344885.jfif",
      descripcion: "Codo de desagüe de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
      usos: "Para desagüe",
      Recomendaciones: "",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "3''",
      presion:"",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo PVC-P sp 1'' 90°", 
      img: "308978.jfif",
      img1:"308978.jfif",
      img2:"308978.jfif",
      img3:"308978.jfif",
      descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
      usos: "Para agua fría",
      Recomendaciones: "",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "1''",
      presion:"10 bar (145 psi)",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo PVC-P c/r 1 1/4'' 90°", 
      img: "309389.jfif",
      img1:"309389.jfif",
      img2:"309389.jfif",
      img3:"309389.jfif",
      descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
      usos: "Para agua fría",
      Recomendaciones: "",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "1 1/4''",
      presion:"10 bar (145 psi)",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo PVC-P c/r 1'' 90°", 
      img: "309397.jfif",
      img1:"309397.jfif",
      img2:"309397.jfif",
      img3:"309397.jfif",
      descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
      usos: "Para agua fría",
      Recomendaciones: "",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "1''",
      presion:"10 bar (145 psi)",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo PVC-P c/r 1'' 90°", 
      img: "309397 (1).jfif",
      img1:"309397 (1).jfif",
      img2:"309397 (1).jfif",
      img3:"309397 (1).jfif",
      descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
      usos: "Para agua fría",
      Recomendaciones: "",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "1''",
      presion:"10 bar (145 psi)",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo Desagüe 1 1/4'' x 45°", 
      img: "2310457.jfif",
      img1:"2310457.jfif",
      img2:"2310457.jfif",
      img3:"2310457.jfif",
      descripcion: "Codo de desagüe de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
      usos: "Para desagüe",
      Recomendaciones: "",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "1 1/4''",
      presion:"560 psi",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo PVC-P c/r 3/4'' 90°", 
      img: "309419.jfif",
      img1:"309419.jfif",
      img2:"309419.jfif",
      img3:"309419.jfif",
      descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
      usos: "Para agua fría",
      Recomendaciones: "",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "3/4''",
      presion:"10 bar (145 psi)",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo PVC-P sp 1 1/2'' 90°", 
      img: "396427.jfif",
      img1:"396427.jfif",
      img2:"396427.jfif",
      img3:"396427.jfif",
      descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
      usos: "Para agua fría",
      Recomendaciones: "",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "1 1/2''",
      presion:"10 bar (145 psi)",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo Desagüe PVC 2'' x 90°", 
      img: "344923.jfif",
      img1:"344923.jfif",
      img2:"344923.jfif",
      img3:"344923.jfif",
      descripcion: "Codo de desagüe de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
      usos: "Para desagüe",
      Recomendaciones: "",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: " 2''",
      presion:"890 psi",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo PVC-P sp 1 1/4'' 90°", 
      img: "30896X.jfif",
      img1:"30896X.jfif",
      img2:"30896X.jfif",
      img3:"30896X.jfif",
      descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
      usos: "Para agua fría",
      Recomendaciones: "",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "1 1/4'' ",
      presion:"10 bar (145 psi)",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo CPVC 1/2'' 90°", 
      img: "308609.jfif",
      img1:"308609.jfif",
      img2:"308609.jfif",
      img3:"308609.jfif",
      descripcion: "Conexión de CPVC están diseñadas para trabajar en forma continua a una presión hidrostática y a temperaturas exigentes.", 
      usos: "Para agua caliente",
      Recomendaciones: "",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "1/2''",
      presion:"100 psi (6.89 bar o 6.8 bar)",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo cachimba PVC 1/2'' 90°", 
      img: "309354.jfif",
      img1:"309354.jfif",
      img2:"309354.jfif",
      img3:"309354.jfif",
      descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
      usos: "Para agua fría",
      Recomendaciones: "",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "1/2''",
      presion:"10 bar (145 psi)",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo PVC-P sp 3/4'' 90°", 
      img: "308994.jfif",
      img1:"308994.jfif",
      img2:"308994.jfif",
      img3:"308994.jfif",
      descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
      usos: "Para agua fría",
      Recomendaciones: "",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "3/4''",
      presion:"10 bar (145 psi)",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo PVC 45° 1/2'' SP", 
      img: "308943.jfif",
      img1:"308943.jfif",
      img2:"308943.jfif",
      img3:"308943.jfif",
      descripcion: "Codo de desagüe de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
      usos: "Para agua fría",
      Recomendaciones: "",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "",
      presion:"",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo Desagüe 3'' x 45°", 
      img: "2680890.jfif",
      img1:"2680890.jfif",
      img2:"2680890.jfif",
      img3:"2680890.jfif",
      descripcion: "Codo de desagüe de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
      usos: "Para desagüe",
      Recomendaciones: "",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "3''",
      presion:"560 psi",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo PVC-P sp 1'' 45°", 
      img: "308935.jfif",
      img1:"308935.jfif",
      img2:"308935.jfif",
      img3:"308935.jfif",
      descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
      usos: "Para agua fría",
      Recomendaciones: "",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "1''",
      presion:"10 bar (145 psi)",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"Codo PVC-P c/r 1 1/2'' 90°", 
      img: "309370.jfif",
      img1:"309370.jfif",
      img2:"309370.jfif",
      img3:"309370.jfif",
      descripcion: "Fabricadas en PVC, para las presiones de trabajo mas exigentes. Las roscas utilizadas son NTP. Resistentes y duraderas.", 
      usos: "Para agua fría",
      Recomendaciones: "",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "1 1/2''",
      presion:"10 bar (145 psi)",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },
    {
      name:"", 
      img: "",
      img1:"",
      img2:"",
      img3:"",
      descripcion: "", 
      usos: "",
      Recomendaciones: "",  
      tipo: "Codo",
      marca: "Pavco",
      material: "PVC",
      Medida: "",
      presion:"",
      Color: "",
      cantidad: "",
      procedencia:"Nacional",
      precio: "",
      precioantes: "0",
      oferta: "0 %",
      categoriageneral: "Gasfiteria",
      categoria: "Conexiones Para Agua"
    },


    // 
    // 
    {
        name:"Adaptador 3/4''", 
        img: "Adaptador  3-4.jfif",
        img1:"Adaptador  3-4.jfif",
        img2:"Adaptador  3-4.jfif",
        img3:"Adaptador  3-4.jfif",
        descripcion: "Adaptador de 3/4''", 
        usos: "Para agua fría",
        Recomendaciones: "Para asegurar la instalación. Utilizar cemento para PVC en la conexión de tipo embone o teflón en la conexión tipo rosca.",  
        tipo: "Adaptador",
        marca: "Tuboplast",
        material: "PVC-U",
        Medidas: "3/4''",
        Color: "Blanco",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Adaptador de 1 cr", 
        img: "208760X.jfif",
        img1:"208760X.jfif",
        img2:"208760X.jfif",
        img3:"208760X.jfif",
        descripcion: "Tubo de acero con sistema roscado, virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
        usos: "Para instalaciones de uso en la construcción.",
        Recomendaciones: "Para asegurar la instalación. Utilizar cemento para PVC en la conexión de tipo embone o teflón en la conexión tipo rosca.",  
        tipo: "Adaptador",
        marca: "Tuboplast",
        material: "PVC-U",
        Medidas: "1''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Adaptador de 1 1/2''", 
        img: "2087863.jfif",
        img1:"2087863.jfif",
        img2:"2087863.jfif",
        img3:"2087863.jfif",
        descripcion: "Adaptador 1 1/2'' C/R. Ideal para agua.", 
        usos: "",
        Recomendaciones: "",  
        tipo: "Adaptador",
        marca: "Tuboplast",
        material: "PVC-U",
        Medidas: "1/2''",
        Color: "Plomo",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Adaptador de 3/4''", 
        img: "2277352.jfif",
        img1:"2277352.jfif",
        img2:"2277352.jfif",
        img3:"2277352.jfif",
        descripcion: "Adaptador de 3/4''", 
        usos: "Para Agua fria",
        Recomendaciones: "Para asegurar la instalación. Utilizar cemento para PVC en la conexión de tipo embone o teflón en la conexión tipo rosca.",  
        tipo: "Adaptador",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "3/4''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      
      {
        name:"Tee de 1 1/2'' C/R", 
        img: "2088231.jfif",
        img1:"2088231.jfif",
        img2:"2088231.jfif",
        img3:"2088231.jfif",
        descripcion: "Tee de 1 1/2'' con rosca", 
        usos: "Abastecer agua de una línea principal a otro punto.",
        Recomendaciones: "",  
        tipo: "Adaptadores",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1 1/2''",
        Color: "Plomo",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
    
      {
        name:"Codo 3/4''", 
        img: "2087405.jfif",
        img1:"2087405.jfif",
        img2:"2087405.jfif",
        img3:"2087405.jfif",
        descripcion: "Tubo de PVC, virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
        usos: "Para agua fría",
        Recomendaciones: "Tubo de PVC, virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.",  
        tipo: "Codo",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "3/4''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Codo 2 x 90 cr", 
        img: "208869X.jfif",
        img1:"208869X.jfif",
        img2:"208869X.jfif",
        img3:"208869X.jfif",
        descripcion: "Material autoextinguible. Cumple norma técnica peruana. NTP 399-006 / PVC-U", 
        usos: "Ideal para distribución de agua.",
        Recomendaciones: "En este tipo de tubería no es recomendable calentar el PVC para unir con otros tubos.",  
        tipo: "Codo",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "2''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Codo de 1 1/4'' SP", 
        img: "2088630.jfif",
        img1:"2088630.jfif",
        img2:"2088630.jfif",
        img3:"2088630.jfif",
        descripcion: "Codo de 1 1/4'' x 90° S/P. Ideal para agua.", 
        usos: "Para uso potable",
        Recomendaciones: "",  
        tipo: "Codo",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1 1/4''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Codo 1''", 
        img: "2087693.jfif",
        img1:"2087693.jfif",
        img2:"2087693.jfif",
        img3:"2087693.jfif",
        descripcion: "Accesorios para cambio de dirección a 45°. 100% resina de PVC virgen. No contiene plomo. Reduce impacto ambiental.", 
        usos: "Ideal para agua fría",
        Recomendaciones: "Para asegurar la instalación utilizar soldadura de PVC en la conexión de tipo embone o teflón en la conexión tipo rosca.",  
        tipo: "Codo",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1''",
        Color: "Plomo",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Codo de 1 1/2'' CR", 
        img: "208788X.jfif",
        img1:"208788X.jfif",
        img2:"208788X.jfif",
        img3:"208788X.jfif",
        descripcion: "Codo de desagüe de PVC con rosca, virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
        usos: "Para desagüe",
        Recomendaciones: "Si la instalación es aérea, el codo debe tener apoy",  
        tipo: "Codo",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1 1/2''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Codo 3/4''", 
        img: "2087685.jfif",
        img1:"2087685.jfif",
        img2:"2087685.jfif",
        img3:"2087685.jfif",
        descripcion: "Accesorios para cambio de dirección a 45°. 100% resina de PVC virgen. No contiene plomo. Reduce impacto ambiental.", 
        usos: "Ideal para agua fría",
        Recomendaciones: "Para asegurar la instalación utilizar soldadura de PVC en la conexión de tipo embone o teflón en la conexión tipo rosca.",  
        tipo: "Codo",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "3/4''",
        Color: "Plomo",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Codo de 1 1/2'' SP", 
        img: "2087898.jfif",
        img1:"2087898.jfif",
        img2:"2087898.jfif",
        img3:"2087898.jfif",
        descripcion: "Codo de PVC. Accesorio para cambio de dirección a 90°.", 
        usos: "Para cambio de dirección a 90°",
        Recomendaciones: "Por el cambio brusco de dirección de recomienda el mayor cuidado en el pegado.",  
        tipo: "Codo",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1 1/2''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Reducción 3/4'' x 1/2'' C/R", 
        img: "208855X.jfif",
        img1:"208855X.jfif",
        img2:"208855X.jfif",
        img3:"208855X.jfif",
        descripcion: "Reducción con rosca exterior-interior. Se usa para cambio de diámetros roscados.", 
        usos: "Ideal para instalaciones de agua",
        Recomendaciones: "No olvidar usar cinta teflón",  
        tipo: "Bushing",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "3/4'' x 1/2''",
        Color: "Plomo",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Bushing 1'' a 3/4''", 
        img: "2088568.jfif",
        img1:"2088568.jfif",
        img2:"2088568.jfif",
        img3:"2088568.jfif",
        descripcion: "Es una reducción rosca exterior-rosca interior.", 
        usos: "Se usa para cambiar diámetros roscados",
        Recomendaciones: "Para asegurar la instalación, utilizar soldadura para PVC en la conexión de tipo embone o teflón en la conexión tipo rosca.",  
        tipo: "Bushing",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1'' a 3/4''",
        Color: "  Plomo",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      
      {
        name:"Codo 90° 1/2''", 
        img: "2087731.jfif",
        img1:"",
        img2:"",
        img3:"",
        descripcion: "Tubo de PVC con sistema roscado, virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
        usos: "Para agua fría",
        Recomendaciones: "No olvidar usar cinta teflón y pegamento de tubería",  
        tipo: "Codo con Rosca",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1/2''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      
      {
        name:"Codo 90° 3/4''", 
        img: "2087766.jfif",
        img1:"2087766.jfif",
        img2:"2087766.jfif",
        img3:"2087766.jfif",
        descripcion: "Tubo de PVC con sistema roscado, virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
        usos: "Para agua fría",
        Recomendaciones: "No olvidar usar cinta teflón y pegamento de tubería",  
        tipo: "Codo con Rosca",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "3/4''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      
      {
        name:"Unión Mixta 1/2'' C-R", 
        img: "2088703.jfif",
        img1:"2088703.jfif",
        img2:"2088703.jfif",
        img3:"2088703.jfif",
        descripcion: "Unión mixta para instalaciones domésticas para unir segmentos de tubos y tuberías con extremos roscados y sin campana (S/P).", 
        usos: "Para unir segmentos de tubos y tuberías",
        Recomendaciones: "Para asegurar la instalación. Utilizar cemento para PVC en la conexión de tipo embone o teflón en la conexión tipo rosca.",  
        tipo: "Conexiones",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1/2''",
        Color: "Plomo",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Unión Mixta 3/4'' C-R", 
        img: "2088711.jfif",
        img1:"2088711.jfif",
        img2:"2088711.jfif",
        img3:"2088711.jfif",
        descripcion: "Unión mixta para instalaciones domésticas para unir segmentos de tubos y tuberías con extremos roscados y sin campana (S/P).", 
        usos: "Para unir segmentos de tubos y tuberías",
        Recomendaciones: "Para asegurar la instalación. Utilizar cemento para PVC en la conexión de tipo embone o teflón en la conexión tipo rosca.",  
        tipo: "Conexiones",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "3/4''",
        Color: "Plomo",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      
    
    
      {
        name:"Niple 2 X 4", 
        img: "2088797.jfif",
        img1:"2088797.jfif",
        img2:"2088797.jfif",
        img3:"2088797.jfif",
        descripcion: "Material de alta resistencia, bajo nivel de corrosión", 
        usos: "Ideal para unir tuberías",
        Recomendaciones: "Utilizar cemento para PVC para asegurar la instalación",  
        tipo: "Niple",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "2x4''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Niple 1 1/2 X 4 PVC", 
        img: "2088770.jfif",
        img1:"2088770.jfif",
        img2:"2088770.jfif",
        img3:"2088770.jfif",
        descripcion: "Material de alta resistencia, bajo nivel de corrosión", 
        usos: "Ideal para unir tuberías",
        Recomendaciones: "Utilizar cemento para PVC para asegurar la instalación",  
        tipo: "Niple",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1 1/2 X 4''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Niple 2 X 6", 
        img: "2088800.jfif",
        img1:"2088800.jfif",
        img2:"2088800.jfif",
        img3:"2088800.jfif",
        descripcion: "Material de alta resistencia, bajo nivel de corrosión", 
        usos: "Ideal para unir tuberías",
        Recomendaciones: "Utilizar cemento para PVC para asegurar la instalación",  
        tipo: "Niple",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "2 X 6''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Niple 1/2 x 3 PVC", 
        img: "2088029 .jfif",
        img1:"2088029 .jfif",
        img2:"2088029 .jfif",
        img3:"2088029 .jfif",
        descripcion: "Material de alta resistencia, bajo nivel de corrosión", 
        usos: "Ideal para unir tuberías",
        Recomendaciones: "Utilizar cemento para PVC para asegurar la instalación",  
        tipo: "Niple",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1/2 x 3''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Niple 1 X 2 PVC", 
        img: "208841X .jfif",
        img1:"208841X .jfif",
        img2:"208841X .jfif",
        img3:"208841X .jfif",
        descripcion: "Material de alta resistencia, bajo nivel de corrosión", 
        usos: "Ideal para unir tuberías",
        Recomendaciones: "Utilizar cemento para PVC para asegurar la instalación",  
        tipo: "Niple",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1 X 2''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Niple 1 1/2 X 6 PVC", 
        img: "2088789 .jfif",
        img1:"2088789 .jfif",
        img2:"2088789 .jfif",
        img3:"2088789 .jfif",
        descripcion: "Material de alta resistencia, bajo nivel de corrosión", 
        usos: "Ideal para unir tuberías",
        Recomendaciones: "Utilizar cemento para PVC para asegurar la instalación",  
        tipo: "Niple",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1 1/2 x 6''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Reducción 1 x 3/4''", 
        img: "208905X.jfif",
        img1:"208905X.jfif",
        img2:"208905X.jfif",
        img3:"208905X.jfif",
        descripcion: "Se utiliza para cambio de diámetro en las tuberías", 
        usos: "Para agua",
        Recomendaciones: "Utilizar pegamento para tuberías para asegurar la instalación",  
        tipo: "Reduccion",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1 x 3/4",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Reducción 1 1/4'' x 1'' sp", 
        img: "2089246.jfif",
        img1:"2089246.jfif",
        img2:"2089246.jfif",
        img3:"2089246.jfif",
        descripcion: "Tubo de PVC, virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
        usos: "Para agua",
        Recomendaciones: "No olvide usar pegamento para tubería.",  
        tipo: "Reduccion",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1 1/4'' x 1''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Reducción 3/4 x 1/2'' SP", 
        img: "2088894.jfif",
        img1:"2088894.jfif",
        img2:"2088894.jfif",
        img3:"2088894.jfif",
        descripcion: "Se utiliza para cambio de diámetro en las tuberías", 
        usos: "Para agua",
        Recomendaciones: "Utilizar pegamento para tuberías para asegurar la instalación",  
        tipo: "Reduccion",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "3/4 x 1/2''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Reducción 2'' x 1 1/4'' sp", 
        img: "2088096.jfif",
        img1:"2088096.jfif",
        img2:"2088096.jfif",
        img3:"2088096.jfif",
        descripcion: "Tubo de PVC, virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
        usos: "ara agua",
        Recomendaciones: "No olvide usar pegamento para tubería.",  
        tipo: "Reduccion",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "2'' x 1 1/4''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Reducción con Rosca 3/4'' x 1/2''", 
        img: "2132389.jfif",
        img1:"2132389.jfif",
        img2:"2132389.jfif",
        img3:"2132389.jfif",
        descripcion: "Reducción con rosca que se utiliza para cambio de diámetro en las tuberías", 
        usos: "Para agua",
        Recomendaciones: "Utilizar pegamento para tuberías para asegurar la instalación",  
        tipo: "Reduccion",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "3/4'' x 1/2''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Reducción de 1'' a 1/2'' Hembra SP", 
        img: "2088576.jfif",
        img1:"2088576.jfif",
        img2:"2088576.jfif",
        img3:"2088576.jfif",
        descripcion: "Reducción Bushing hembra de 1'' a 1/2'' S/P. Ideal para agua potable.", 
        usos: "Para Agua Fría",
        Recomendaciones: "No olvidar utilizar cinta teflón.",  
        tipo: "Reduccion",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1'' a 1/2''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Reducción para Desagüe 2'' x 1 1/2''", 
        img: "208810X.jfif",
        img1:"208810X.jfif",
        img2:"208810X.jfif",
        img3:"208810X.jfif",
        descripcion: "Reducción para cambio de diámetro", 
        usos: "Para desagüe",
        Recomendaciones: "",  
        tipo: "Reduccion",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "2'' x 1 1/2''",
        Color: "Plomo orgánico",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Reducción 1'' x 3/4'' SP", 
        img: "208905X (1).jfif",
        img1:"208905X (1).jfif",
        img2:"208905X (1).jfif",
        img3:"208905X (1).jfif",
        descripcion: "Se utiliza para cambio de diámetro en las tuberías", 
        usos: "Para agua",
        Recomendaciones: "Utilizar pegamento para tuberías para asegurar la instalación",  
        tipo: "Reduccion",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1'' x 3/4''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Reducción 3'' x 2'' Desagüe", 
        img: "2088118.jfif",
        img1:"2088118.jfif",
        img2:"2088118.jfif",
        img3:"2088118.jfif",
        descripcion: "Tubo de PVC, virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
        usos: "",
        Recomendaciones: "No olvide usar pegamento para tubería.",  
        tipo: "Reduccion",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "3'' x 2''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Reducción 1'' x 1/2'' SP", 
        img: "2089041 (1).jfif",
        img1:"2089041 (1).jfif",
        img2:"2089041 (1).jfif",
        img3:"2089041 (1).jfif",
        descripcion: "Se utiliza para cambio de diámetro en las tuberías", 
        usos: "Para Agua",
        Recomendaciones: "Utilizar pegamento para tuberías para asegurar la instalación",  
        tipo: "Reduccion",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1'' x 1/2'' ",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Tapón 1'' Macho cr", 
        img: "208757X.jfif",
        img1:"208757X.jfif",
        img2:"208757X.jfif",
        img3:"208757X.jfif",
        descripcion: "Tapón macho de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
        usos: "Para agua fría",
        Recomendaciones: "Para asegurar la instalación. Utilizar cemento para PVC en la conexión de tipo embone o teflón en la conexión tipo rosca.",  
        tipo: "Tapón",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Tapón Hembra 1 SP", 
        img: "2087847.jfif",
        img1:"2087847.jfif",
        img2:"2087847.jfif",
        img3:"2087847.jfif",
        descripcion: "Se usa para sellar. Se instala en un tubo sin campana.", 
        usos: "Para agua",
        Recomendaciones: "Utilizar pegamento para tuberías para asegurar la instalación",  
        tipo: "Tapón",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Tapón para Desagüe de 4''", 
        img: "2088223.jfif",
        img1:"2088223.jfif",
        img2:"2088223.jfif",
        img3:"2088223.jfif",
        descripcion: "Tapón de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
        usos: "Para sellar una línea de tubería o circuito.",
        Recomendaciones: "Utilizar soldadura de PVC.",  
        tipo: "Tapon",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "4''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Tee 1'' SP", 
        img: "2087650.jfif",
        img1:"2087650.jfif",
        img2:"2087650.jfif",
        img3:"2087650.jfif",
        descripcion: "Se usa para instalaciones domésticas.", 
        usos: "Para desagüe",
        Recomendaciones: "Para asegurar la instalación utilizar soldadura de PVC",  
        tipo: "Tee",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "33 mm",
        diametro:"1''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Tee 2'' sp", 
        img: "2088495.jfif",
        img1:"2088495.jfif",
        img2:"2088495.jfif",
        img3:"2088495.jfif",
        descripcion: "Tee de desagüe de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
        usos: "Para desagüe",
        Recomendaciones: "No olvidar usar cinta teflón y pegamento de tubería",  
        tipo: "Tee",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "2''",
        Color: "Gris Organico",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Tee PVC 1''", 
        img: "2277379.jfif",
        img1:"2277379.jfif",
        img2:"2277379.jfif",
        img3:"2277379.jfif",
        descripcion: "Tee 100% resina de PVC virgen. No contiene plomo. Reduce impacto ambienta", 
        usos: "Para agua fría",
        Recomendaciones: "Para asegurar la instalación utilizar soldadura de PVC",  
        tipo: "Tee",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Tee de 1 1/2'' SP", 
        img: "208824X.jfif",
        img1:"208824X.jfif",
        img2:"208824X.jfif",
        img3:"208824X.jfif",
        descripcion: "Tee de 1 1/2'' SP. Accesorio de 90°. Se usa para abastecer de agua de una línea principal a otro punto.", 
        usos: "Abastecer de agua una línea principal a otro punto.",
        Recomendaciones: "No olvidar usar cinta teflón.",  
        tipo: "Tee",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1 1/2''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Unión de 1/2''", 
        img: "2277301.jfif",
        img1:"2277301.jfif",
        img2:"2277301.jfif",
        img3:"2277301.jfif",
        descripcion: "Unión 1/2'' PVC S/P presión.", 
        usos: "",
        Recomendaciones: "Para asegurar la instalación utilizar soldadura de PVC en la conexión.",  
        tipo: "Uniones",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1/2''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Unión de 3/4''", 
        img: "2277336.jfif",
        img1:"2277336.jfif",
        img2:"2277336.jfif",
        img3:"2277336.jfif",
        descripcion: "Unión 3/4'' PVC S/P presión.", 
        usos: "",
        Recomendaciones: "Para asegurar la instalación utilizar soldadura de PVC en la conexión.",  
        tipo: "Uniones",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "3/4''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Unión de 1'' ", 
        img: "2277387.jfif",
        img1:"2277387.jfif",
        img2:"2277387.jfif",
        img3:"2277387.jfif",
        descripcion: "Unión 1'' PVC C-10 S/P presión.", 
        usos: "",
        Recomendaciones: "Para asegurar la instalación utilizar soldadura de PVC en la conexión.",  
        tipo: "Uniones",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Unión Universal de 1/2'' SP", 
        img: "2087715.jfif",
        img1:"2087715.jfif",
        img2:"2087715.jfif",
        img3:"2087715.jfif",
        descripcion: "Se usa en instalaciones domésticas para unir tuberías y segmentos de tubos. Su diseño permite el desacoplamiento fácil del sistema instalado para cualquier reparación, modificación o mantenimiento.", 
        usos: "Para agua",
        Recomendaciones: "Para asegurar la instalación utilizar cemento para PVC en la conexión.",  
        tipo: "union universal",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1/2''",
        Color: "Blanco",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Unión Universal 1'' SP", 
        img: "2087707.jfif",
        img1:"2087707.jfif",
        img2:"2087707.jfif",
        img3:"2087707.jfif",
        descripcion: "Su diseño permite el desacoplamiento fácil del sistema instalado para cualquier reparación, modificación o mantenimiento.", 
        usos: "Ideal para instalaciones domésticas para unir tuberías y segmentos de tubos.",
        Recomendaciones: "Utilizar pegamento para tuberías para asegurar la instalación",  
        tipo: "union universal",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Tubo 1/2'' x 5 m sp", 
        img: "2087618.jfif",
        img1:"2087618.jfif",
        img2:"2087618.jfif",
        img3:"2087618.jfif",
        descripcion: "Tubo de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
        usos: "Para agua fría",
        Recomendaciones: "No olvidar usar cinta teflón y pegamento de tubería",  
        tipo: "",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1/2'' x 5 m ",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Tubo de 3/4'' x 5 m sp", 
        img: "2087626.jfif",
        img1:"2087626.jfif",
        img2:"2087626.jfif",
        img3:"2087626.jfif",
        descripcion: "Tubo de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
        usos: "Para agua fría",
        Recomendaciones: "No olvidar usar cinta teflón y pegamento de tubería",  
        tipo: "",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "3/4'' x 5 m ",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Unión de 1 1/2'' CR", 
        img: "2088320.jfif",
        img1:"2088320.jfif",
        img2:"2088320.jfif",
        img3:"2088320.jfif",
        descripcion: "Unión de 1 1/2'' C/R. Ideal para cañerías de agua.", 
        usos: "",
        Recomendaciones: "Para asegurar la instalación utilizar soldadura de PVC en la conexión.",  
        tipo: "uniones y conexiones",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1 1/2'' ",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Tee 1/2'' SP", 
        img: "2087413.jfif",
        img1:"2087413.jfif",
        img2:"2087413.jfif",
        img3:"2087413.jfif",
        descripcion: "Accesorio que permite recibir aguas servidas en 2 puntos. La entrada y la desviación es una curva de 90°. Permite que el encuentro de la caída de agua de los dos puntos en común no sea en forma brusca. 100% resina de PVC virgen. No contiene plomo. Resistente y funcional.", 
        usos: "Para desagüe",
        Recomendaciones: "Para asegurar la instalación utilizar soldadura de PVC en la conexión.",  
        tipo: "Tee Sanitaria",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1/2''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Tee 1'' con rosca", 
        img: "2087790.jfif",
        img1:"2087790.jfif",
        img2:"2087790.jfif",
        img3:"2087790.jfif",
        descripcion: "Fabricado de PVC virgen sin estabilizante de plomo, lo cual reduce el impacto ambiental.", 
        usos: "Para agua fría",
        Recomendaciones: "Para asegurar la instalación. Utilizar cemento para PVC en la conexión de tipo embone o teflón en la conexión tipo rosca.",  
        tipo: "Tee con rosca",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Curva 1/2'' x 90", 
        img: "2087952.jfif",
        img1:"2087952.jfif",
        img2:"2087952.jfif",
        img3:"2087952.jfif",
        descripcion: "Material autoextinguible. Cumple norma técnica peruana. NTP 399-006 / PVC-U", 
        usos: "Ideal para proteger los cables eléctricos.",
        Recomendaciones: "Es recomendable rasgar el PVC para una mayor adherencia al contacto con otros tubos.",  
        tipo: "Curva",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "1/2''",
        Color: "Gris",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Cachimba 200mm a 160mm PVC", 
        img: "2153327.jfif",
        img1:"2153327.jfif",
        img2:"2153327.jfif",
        img3:"2153327.jfif",
        descripcion: "", 
        usos: "Para desagüe",
        Recomendaciones: "",  
        tipo: "Cachimbas",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "200 mm a 160 mm",
        Color: "",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
      {
        name:"Codo 90'' x 160 mm", 
        img: "2088983.jfif",
        img1:"2088983.jfif",
        img2:"2088983.jfif",
        img3:"2088983.jfif",
        descripcion: "Tubo de alcantarillado de PVC-U, con estabilizante de estaño o calcio-zinc sin plomo, lo cual reduce el impacto ambiental.", 
        usos: "",
        Recomendaciones: "Tener cuidado en la carga, transporte y descarga del material",  
        tipo: "Para alcantarillado",
        marca: "Tuboplast",
        material: "PVC",
        Medida: "160 mm",
        Color: "",
        cantidad: "",
        procedencia:"Nacional",
        precio: "",
        precioantes: "0",
        oferta: "0 %",
        categoriageneral: "Gasfiteria",
        categoria: "Conexiones Para Agua"
      },
    
    
  ];
  
  